FROM node:22-bookworm-slim

# ENV NODE_ENV production

WORKDIR /app

RUN chown -R node:node /app

COPY --chown=node:node . .

USER node

RUN npm i

# disable notifier warning
RUN npm config set update-notifier false

CMD ["npm", "run", "start"]
